urls:
  - gnome://:
      - tag: desktop

  - dbus://:
      - tag: desktop

  - tgram://:
      - bot_token: "bottoken"
      - chat_id: "chatid"
      - image: Yes
      - tag: mobile

  - twitter://:
      - ScreenName: "ScreenName"
      - ConsumerKey: "ConsumerKey"
      - ConsumerSecret: "ConsumerSecret"
      - AccessToken: "AccessToken"
      - AccessSecret: "AccessSecret"
      - tag: social
