#
# Minimal Configuration Example
#

# Define your URLs
urls:
  # Either on-line each entry like this:
  - json://localhost
  - xml://localhost

  # Or add a colon to the end of the URL where you can optionally provide
  # over-ride entries.  One of the most likely entry to be used here
  # is the tag entry.  This gets extended to the global tag (if defined)
  # above
  - windows://:
      # 'tag' is a special keyword that allows you to associate tags with your
      # services:
      - tag: desktop

  - tgram://:
      - bot_token: bottoken
      - chat_id: chatid
      - image: yes

  - twitter://:
      - ScreenName: ScreenName
      - ConsumerKey: ConsumerKey
      - ConsumerSecret: ConsumerSecret
      - AccessToken: AccessToken
      - AccessSecret: AccessSecret
