[theme]

[theme.options]
#---not used---
#is_display = true
#display = "waveshare27inch"
#resolution = [264, 176]
#hi-res = true
#bg = true
#-------------

bg_image = "ui-bg-w27.png"
font_sizes = [10, 9, 10, 35, 25, 9]
label_spacing = 9 # not linked yet
fps = 0 # not linked yet
font = 'DejaVuSansMono'
status_font = 'DejaVuSansMono'

cursor = '❤'

# 'full' = full color mode
# '2' = 2 colors mode (1bit)
# '3' = 3 colors mode (grayscale)
color_web = 'full'
color_display = '3'

# what will be the text color for a low color display
# 'black'
# 'white'
# 'auto' = pale color will be 'white' and dark color will be 'black'
color_text = 'black'

[theme.main_elements]

[theme.main_elements.face]
position = [66, 27]
font = "Huge"
color = "magenta"

[theme.main_elements.name]
position = [5, 73]
font = "Bold"
color = "lime"

# Exemple test to add icons to an element label/value
#[theme.main_elements.test_icon]
#position = [0, 18]
#label_icon = true
#label = ["/.../.../.../icon.png"]
#value_icon = true
#value = ["/.../.../.../icon2.png", "/.../.../.../icon3.png"]
#label_font = "Bold"
#text_font = "Medium"
#color = "BLACK"

[theme.main_elements.channel]
position = [0, 0]
label = "CH"
value = "00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.aps]
position = [28, 0]
label = "APS"
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.uptime]
position = [199, 0]
label = "UP"
value = "00:00:00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.line1]
position = [0, 14, 264, 14]
color = "lime"

[theme.main_elements.line2]
position = [0, 162, 264, 162]
color = "lime"

[theme.main_elements.friend_face]
position = [0, 146]
font = "Bold"
color = "lime"

[theme.main_elements.friend_name]
position = [40, 146]
font = "BoldSmall"
color = "lime"

[theme.main_elements.shakes]
position = [0, 163]
label = "PWND "
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.mode]
position = [239, 163]
value = "AUTO"
font = "Bold"
color = "lime"

[theme.main_elements.status]
position = [38, 93]
value = "AUTO"
font = "Medium"
color = "lime"
wrap = true
max = 20

[theme.plugin_elements]

[theme.plugin_elements.crack_house]

[theme.plugin_elements.crack_house.crack_house]
position = [-10, 185]
label_font = "Bold"
text_font = "Small"
color = "BLACK"

[theme.plugin_elements.crack_house.crack_house_stats]
position = [-10, 170]
label_font = "Bold"
text_font = "Small"
color = "BLACK"
