[theme]

[theme.options]
#---not used---
#is_display = true
#display = "lcdhat"
#resolution = [240, 240]
#hi-res = true
#bg = true
#-------------

bg_image = "ui-bg-b.png"#"240x240-b.png"
font_sizes = [14, 12, 14, 32, 29, 13]
label_spacing = 9
fps = 3 
font = 'DejaVuSansMono'
status_font = 'DejaVuSansMono'

cursor = '❤'

# color mode for the web UI and the display
# 'full' = full color mode
# '2' = 2 colors mode (1bit)
# '3' = 3 colors mode (grayscale)
color_web = 'full'
color_display = 'full'

# what will be the text color for a low color display
# 'black'
# 'white'
# 'auto' = pale color will be 'white' and dark color will be 'black'
color_text = 'white'

[theme.main_elements]

[theme.main_elements.face]
position = [60, 40]
font = "Huge"
color = "lime"

[theme.main_elements.name]
position = [0, 78]
font = "Bold"
color = "white"

# Exemple test to add icons to an element label/value
#[theme.main_elements.test_icon]
#position = [0, 18]
#label_icon = true
#label = ["/.../.../.../icon.png"]
#value_icon = true
#value = ["/.../.../.../icon2.png", "/.../.../.../icon3.png"]
#label_font = "Bold"
#text_font = "Medium"
#color = "BLACK"

[theme.main_elements.channel]
position = [0, 18]
label = "CH"
value = "00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.aps]
position = [35, 18]
label = "APS"
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.uptime]
position = [153, 18]
label = "UP"
value = "00:00:00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.line1]
position = [0, -1, 240, -1]
color = "lime"

[theme.main_elements.line2]
position = [0, -1, 240, -1]
color = "lime"

[theme.main_elements.friend_face]
position = [10, 223]
font = "Bold"
color = "lime"

[theme.main_elements.friend_name]
position = [60, 226]
font = "BoldSmall"
color = "lime"

[theme.main_elements.shakes]
position = [0, 152]
label = "PWND "
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.mode]
position = [100, 36]
value = "AUTO"
font = "Bold"
color = "lime"

[theme.main_elements.status]
position = [10,98]
value = "AUTO"
font = "Medium"
color = "lime"
wrap = true
max = 20

[theme.plugin_elements]

[theme.plugin_elements.crack_house]

[theme.plugin_elements.crack_house.crack_house]
position = [-10, 185]
label_font = "Bold"
text_font = "Small"
color = "BLACK"

[theme.plugin_elements.crack_house.crack_house_stats]
position = [-10, 170]
label_font = "Bold"
text_font = "Small"
color = "BLACK"
